replicaCount: 1
image:
  repository: gitlab.com/hellofresh-canada/hfcp-rack-backend/
  tag: stable
  pullPolicy: Always
  secrets:
    - name: gitlab-registry
podAnnotations: {}
application:
  track: stable
  tier: web
  migrateCommand:
  initializeCommand:
  secretName:
  secretChecksum:
gitlab:
  app:
  env:
service:
  enabled: true
  annotations: {}
  name: web
  type: ClusterIP
  url:
  additionalHosts:
  commonName:
  externalPort: 80
  internalPort: 80
ingress:
  tls:
    enabled: true
    secretName: ""
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "18000"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "18000"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "14400"
livenessProbe:
  path: "/health"
  initialDelaySeconds: 15
  timeoutSeconds: 15
  scheme: "HTTP"
readinessProbe:
  path: "/health"
  initialDelaySeconds: 5
  timeoutSeconds: 3
  scheme: "HTTP"
podDisruptionBudget:
  enabled: false
  maxUnavailable: 1
