image: alpine:latest

variables:
  STAGING_ENABLED: "true"
  CODE_QUALITY_DISABLED: "true"
  TEST_DISABLED: "true"

  KUBERNETES_VERSION: 1.15.5
  HELM_VERSION: 2.14.3

  DOCKER_DRIVER: overlay2

  ROLLOUT_RESOURCE_TYPE: deployment
  PACKAGE_PATH: /go/src/gitlab.com/hellofresh-canada/hfca-bob-rest

stages:
  - build
  - test
  - deploy
  - staging
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - cleanup

include:
  - template: Jobs/Build.gitlab-ci.yml
  - local: Jobs/Test.gitlab-ci.yml
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - local: Jobs/Deploy.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Management.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml