.inject-gopath: &inject-gopath
                  mkdir -p $(dirname ${PACKAGE_PATH})
                  && ln -s ${CI_PROJECT_DIR} ${PACKAGE_PATH}
                  && cd ${PACKAGE_PATH}

test:
  stage: test
  image: golang:1.13.8-alpine3.11
  before_script:
    - *inject-gopath
  environment:
    name: test
  script:
    - CGO_ENABLED=0 GOOS=linux go test -v ./... -coverprofile .testCoverage.txt
  only:
    - branches
    - tags

  except:
    variables:
      - $TEST_DISABLED
